name: coverage

on:
  push:
    paths:
      - 'streamable/**'
      - 'tests/**'
      - '.github/workflows/coverage.yml'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: unittest
        run: |
          python -m pip install -r requirements-dev.txt
          coverage run -m unittest
        
      - name: Generate coverage report
        run: coverage report --fail-under=100  # Adjust minimum coverage threshold as needed

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

