name: test

on: [push]

jobs:
  unittest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: unittest
      run: |
        python -m unittest

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: unittest
      run: |
        python -m pip install black==23.7.0
        python -m black --check kioss/* test/*
